name: "PHP 7.3 - Docker build and push"

on:
  push:
    paths:
      - '7.3/**'
    branches:
      - "master"

jobs:
  docker:
    name: "Docker build and push"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        tags:
          - '7.3'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.tags }}
          push: true
          tags: adlacruzes/php-ci:${{ matrix.tags }}
